image:
  repository: 589389425618.dkr.ecr.us-east-1.amazonaws.com/payment-service
  tag: "latest"

replicaCount: 2

resources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  - name: SERVICE_NAME
    value: "payment-service"
  - name: FAILURE_RATE
    value: "0.0"
  - name: SIMULATE_LATENCY
    value: "false"
